flags:
  synquid:
    synquid: true
packages:
  - '.'
resolver: nightly-2022-05-05
extra-deps:
  - z3-408.2
extra-include-dirs:
 - /opt/homebrew/include
extra-lib-dirs:
 - /opt/homebrew/lib
